{
  "name": "SemanticModel",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "collation": "Latin1_General_100_BIN2_UTF8",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_date",
        "lineageTag": "baef737f-27d0-4f8b-980c-ce2d6307ae75",
        "columns": [
          {
            "name": "date_key",
            "dataType": "dateTime",
            "sourceColumn": "date_key",
            "lineageTag": "bc580fae-551f-4096-af52-2d4034166c2e",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "lineageTag": "da5fa096-969f-4e49-8e45-e513486362cd",
            "summarizeBy": "sum"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "lineageTag": "546923e7-3319-426e-8db0-aa05fb525f53",
            "summarizeBy": "none"
          },
          {
            "name": "month_no",
            "dataType": "int64",
            "sourceColumn": "month_no",
            "lineageTag": "26c417dd-ee43-4abb-ad5d-0b5c4b13f086",
            "summarizeBy": "sum"
          },
          {
            "name": "month_name",
            "dataType": "string",
            "sourceColumn": "month_name",
            "lineageTag": "96ad2d57-2d60-4723-828d-b3a218b71b28",
            "summarizeBy": "none"
          },
          {
            "name": "year_month",
            "dataType": "string",
            "sourceColumn": "year_month",
            "lineageTag": "558b8f5e-0b2f-43a6-a64d-97edd6c2204a",
            "summarizeBy": "none",
            "sortByColumn": "year_month_sort"
          },
          {
            "name": "fy_label",
            "dataType": "string",
            "sourceColumn": "fy_label",
            "lineageTag": "2ed8487b-2b2e-414a-94c1-6ba769cdfd5a",
            "summarizeBy": "none"
          },
          {
            "name": "year_month_sort",
            "dataType": "int64",
            "sourceColumn": "year_month_sort",
            "lineageTag": "129659d6-86a4-4c93-afc2-9a1702fde25a",
            "summarizeBy": "sum"
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "lineageTag": "593c0879-a07d-4e72-a67e-a1cf500aa512",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          }
        ],
        "partitions": [
          {
            "name": "dim_date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\dim_date.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"date_key\", type date}, {\"year\", Int64.Type}, {\"quarter\", type text}, {\"month_no\", Int64.Type}, {\"month_name\", type text}, {\"year_month\", type text}, {\"fy_label\", type text}, {\"year_month_sort\", Int64.Type}, {\"date\", type date}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "dataCategory": "Time"
      },
      {
        "name": "dim_market",
        "lineageTag": "038e4e84-834c-4561-8e3d-1e6f0a96d0ed",
        "columns": [
          {
            "name": "market_key",
            "dataType": "string",
            "sourceColumn": "market_key",
            "lineageTag": "4bfa0243-7203-457f-acc2-bca60fb51889",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "market",
            "dataType": "string",
            "sourceColumn": "market",
            "lineageTag": "fd7bf07e-4f96-4a35-9ee4-b1d3b12f4211",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "lineageTag": "9f1eee83-6444-4699-9fbc-b5ab8c45a14e",
            "summarizeBy": "none"
          },
          {
            "name": "tracked_separately",
            "dataType": "string",
            "sourceColumn": "tracked_separately",
            "lineageTag": "d29796f8-4b6d-41ea-91c0-ce130c77953f",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "dim_market",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\dim_market.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"market_key\", type text}, {\"market\", type text}, {\"region\", type text}, {\"tracked_separately\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_orders",
        "lineageTag": "9422b313-1a6e-4a49-81d2-c90fa0bb06fc",
        "columns": [
          {
            "name": "order_id",
            "dataType": "string",
            "sourceColumn": "order_id",
            "lineageTag": "ca65d533-b016-466b-8f73-d9780e5c89b9",
            "summarizeBy": "none"
          },
          {
            "name": "market",
            "dataType": "string",
            "sourceColumn": "market",
            "lineageTag": "24a5362d-4252-4b9f-a91c-be4379e9c4ef",
            "summarizeBy": "none"
          },
          {
            "name": "booked_key",
            "dataType": "dateTime",
            "sourceColumn": "booked_key",
            "lineageTag": "e30ffe96-ab67-4d7e-b578-7c8f6c7b5ed6",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd",
            "isHidden": true
          },
          {
            "name": "expected_key",
            "dataType": "dateTime",
            "sourceColumn": "expected_key",
            "lineageTag": "2c2b746d-8a1e-4d9e-b34a-18e277a8d627",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd",
            "isHidden": true
          },
          {
            "name": "actual_key",
            "dataType": "dateTime",
            "sourceColumn": "actual_key",
            "lineageTag": "a945a01c-d57e-4c40-becd-6999df82d00b",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd",
            "isHidden": true
          },
          {
            "name": "mw",
            "dataType": "double",
            "sourceColumn": "mw",
            "lineageTag": "ade794fe-e7e1-4b25-b4e2-4c7b3ca752f0",
            "summarizeBy": "sum"
          },
          {
            "name": "order_value",
            "dataType": "double",
            "sourceColumn": "order_value",
            "lineageTag": "a5f50ff3-db3f-458b-98c9-dface37529ed",
            "summarizeBy": "sum"
          },
          {
            "name": "material_committed",
            "dataType": "double",
            "sourceColumn": "material_committed",
            "lineageTag": "3c33e5da-ff95-4f04-9ebd-bdb4e5822719",
            "summarizeBy": "sum"
          },
          {
            "name": "promised_months",
            "dataType": "int64",
            "sourceColumn": "promised_months",
            "lineageTag": "e0209206-e0ac-4ed9-b7cb-86b8ea4c57cf",
            "summarizeBy": "sum"
          },
          {
            "name": "slip_months",
            "dataType": "double",
            "sourceColumn": "slip_months",
            "lineageTag": "5f362bdf-7ef6-4376-bc6c-25cf06e466ff",
            "summarizeBy": "sum"
          },
          {
            "name": "cancelled",
            "dataType": "boolean",
            "sourceColumn": "cancelled",
            "lineageTag": "5adf8c18-e822-4a0c-96c4-6e1bad461137",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "dataType": "string",
            "sourceColumn": "status",
            "lineageTag": "0555acb1-5a85-4b29-80f2-a0159edcd393",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "fact_orders",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\fact_orders.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"order_id\", type text}, {\"market\", type text}, {\"booked_key\", type date}, {\"expected_key\", type date}, {\"actual_key\", type date}, {\"mw\", type number}, {\"order_value\", type number}, {\"material_committed\", type number}, {\"promised_months\", Int64.Type}, {\"slip_months\", type number}, {\"cancelled\", type logical}, {\"status\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "isHidden": false
      },
      {
        "name": "fact_forecast",
        "lineageTag": "6e47885f-c7ee-4f7b-b2e8-bc1d9a26bc84",
        "columns": [
          {
            "name": "month",
            "dataType": "dateTime",
            "sourceColumn": "month",
            "lineageTag": "222220a7-7735-4891-9707-1eca8539a7ca",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "date_key",
            "dataType": "dateTime",
            "sourceColumn": "date_key",
            "lineageTag": "1208c66d-5635-4f82-9840-07a48c696452",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "scope",
            "dataType": "string",
            "sourceColumn": "scope",
            "lineageTag": "46a06961-69ef-4218-85c9-655dfb2ac7b6",
            "summarizeBy": "none"
          },
          {
            "name": "layer",
            "dataType": "string",
            "sourceColumn": "layer",
            "lineageTag": "ab14b6fc-f104-4ff0-ac3b-ae7aa26a4b71",
            "summarizeBy": "none"
          },
          {
            "name": "p10",
            "dataType": "double",
            "sourceColumn": "p10",
            "lineageTag": "e4758d1b-7c69-410d-a199-8d47079a1cef",
            "summarizeBy": "sum"
          },
          {
            "name": "p25",
            "dataType": "double",
            "sourceColumn": "p25",
            "lineageTag": "af5b484a-9aa3-420d-93f3-5d5a7f3b6141",
            "summarizeBy": "sum"
          },
          {
            "name": "p50",
            "dataType": "double",
            "sourceColumn": "p50",
            "lineageTag": "e8af5041-22d6-4fc0-8e38-53669cfa86ca",
            "summarizeBy": "sum"
          },
          {
            "name": "p75",
            "dataType": "double",
            "sourceColumn": "p75",
            "lineageTag": "c5293f5b-100c-4040-b7ab-810ac5737511",
            "summarizeBy": "sum"
          },
          {
            "name": "p90",
            "dataType": "double",
            "sourceColumn": "p90",
            "lineageTag": "a2bc9f9e-b085-4079-840c-c12fb94b1769",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "fact_forecast",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\fact_forecast.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"month\", type date}, {\"date_key\", type date}, {\"scope\", type text}, {\"layer\", type text}, {\"p10\", type number}, {\"p25\", type number}, {\"p50\", type number}, {\"p75\", type number}, {\"p90\", type number}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "isHidden": false
      },
      {
        "name": "fact_coverage",
        "lineageTag": "6b0d898f-f660-4755-8f01-70fbf45716a4",
        "columns": [
          {
            "name": "cutoff",
            "dataType": "dateTime",
            "sourceColumn": "cutoff",
            "lineageTag": "242a0053-e88d-4400-bdac-e50ef8f204d2",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "month",
            "dataType": "dateTime",
            "sourceColumn": "month",
            "lineageTag": "a84c92df-d8b4-4754-bef0-51a0878cf1f8",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "cutoff_key",
            "dataType": "dateTime",
            "sourceColumn": "cutoff_key",
            "lineageTag": "25457ba1-ba76-41e9-ac3e-557be691b1e6",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd",
            "isHidden": true
          },
          {
            "name": "date_key",
            "dataType": "dateTime",
            "sourceColumn": "date_key",
            "lineageTag": "f8e47d46-0f9f-42ca-ac55-f45ea35a2cdd",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "months_ahead",
            "dataType": "int64",
            "sourceColumn": "months_ahead",
            "lineageTag": "68999285-b888-4745-a6bb-e83d8f60a061",
            "summarizeBy": "sum"
          },
          {
            "name": "actual",
            "dataType": "double",
            "sourceColumn": "actual",
            "lineageTag": "47d86251-8cf4-49f8-88b6-027d2249f994",
            "summarizeBy": "sum"
          },
          {
            "name": "p10",
            "dataType": "double",
            "sourceColumn": "p10",
            "lineageTag": "677c681d-e840-4752-a281-11db87a11bdb",
            "summarizeBy": "sum"
          },
          {
            "name": "p25",
            "dataType": "double",
            "sourceColumn": "p25",
            "lineageTag": "8058d844-79ce-4de8-abf6-7164534bf487",
            "summarizeBy": "sum"
          },
          {
            "name": "p50",
            "dataType": "double",
            "sourceColumn": "p50",
            "lineageTag": "67484cfb-3022-4844-a71c-9b8b82b36aef",
            "summarizeBy": "sum"
          },
          {
            "name": "p75",
            "dataType": "double",
            "sourceColumn": "p75",
            "lineageTag": "53a3fa34-62e9-4fb0-82b0-79aadee6f1d6",
            "summarizeBy": "sum"
          },
          {
            "name": "p90",
            "dataType": "double",
            "sourceColumn": "p90",
            "lineageTag": "3705007c-48f7-4eab-bfbd-1a332c0f4109",
            "summarizeBy": "sum"
          },
          {
            "name": "error",
            "dataType": "double",
            "sourceColumn": "error",
            "lineageTag": "a304d031-d05c-4e67-9638-a28eeb3fc882",
            "summarizeBy": "sum"
          },
          {
            "name": "inside_80",
            "dataType": "int64",
            "sourceColumn": "inside_80",
            "lineageTag": "1210f086-6551-4a19-af32-f568478e1750",
            "summarizeBy": "sum"
          },
          {
            "name": "inside_50",
            "dataType": "int64",
            "sourceColumn": "inside_50",
            "lineageTag": "1b4152e8-737a-4a2c-9499-7c50f16065e4",
            "summarizeBy": "sum"
          },
          {
            "name": "direction",
            "dataType": "string",
            "sourceColumn": "direction",
            "lineageTag": "2feec3ea-35b0-4e12-ac59-8d9fd2e5c611",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "fact_coverage",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\fact_coverage.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"cutoff\", type date}, {\"month\", type date}, {\"cutoff_key\", type date}, {\"date_key\", type date}, {\"months_ahead\", Int64.Type}, {\"actual\", type number}, {\"p10\", type number}, {\"p25\", type number}, {\"p50\", type number}, {\"p75\", type number}, {\"p90\", type number}, {\"error\", type number}, {\"inside_80\", Int64.Type}, {\"inside_50\", Int64.Type}, {\"direction\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "isHidden": false
      },
      {
        "name": "fact_lookback",
        "lineageTag": "14e45ae5-698a-43d9-8e9b-781c6e791eec",
        "columns": [
          {
            "name": "market",
            "dataType": "string",
            "sourceColumn": "market",
            "lineageTag": "c6ad3731-62d0-4508-a927-b20c70c26f92",
            "summarizeBy": "none"
          },
          {
            "name": "month",
            "dataType": "dateTime",
            "sourceColumn": "month",
            "lineageTag": "d24bf33e-038a-4635-b158-9504b7c137e2",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "date_key",
            "dataType": "dateTime",
            "sourceColumn": "date_key",
            "lineageTag": "58ee2fbb-5b7a-45af-bd3b-8364e241923a",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "expected_mw",
            "dataType": "double",
            "sourceColumn": "expected_mw",
            "lineageTag": "23d49c5a-8b6d-45a8-b338-113e27ce2ede",
            "summarizeBy": "sum"
          },
          {
            "name": "actual_mw",
            "dataType": "double",
            "sourceColumn": "actual_mw",
            "lineageTag": "67b71377-cb9e-45ac-9f36-7cc340b9e889",
            "summarizeBy": "sum"
          },
          {
            "name": "realization",
            "dataType": "double",
            "sourceColumn": "realization",
            "lineageTag": "7189e672-c281-4231-8842-72de9905288e",
            "summarizeBy": "sum"
          },
          {
            "name": "bias_mw",
            "dataType": "double",
            "sourceColumn": "bias_mw",
            "lineageTag": "987d45d5-3872-42d7-986d-bda2f33985f1",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "fact_lookback",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\fact_lookback.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"market\", type text}, {\"month\", type date}, {\"date_key\", type date}, {\"expected_mw\", type number}, {\"actual_mw\", type number}, {\"realization\", type number}, {\"bias_mw\", type number}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "isHidden": false
      },
      {
        "name": "Realization Scenario",
        "lineageTag": "e445f191-7f35-46f0-b76d-4784d9f3262a",
        "columns": [
          {
            "name": "Realization Scenario",
            "dataType": "double",
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Realization Scenario]",
            "formatString": "0%",
            "lineageTag": "c01b2b60-c409-4441-9905-d515d76db36e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Realization Scenario",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "SELECTCOLUMNS (\n    GENERATESERIES ( 0.55, 1, 0.05 ),\n    \"Realization Scenario\", [Value]\n)"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1aa5b94c3f8345258c9b2941b7c40555"
          }
        ]
      },
      {
        "name": "S&OP Metrics",
        "lineageTag": "2650b709-feeb-42d7-837d-a61160fe5172",
        "columns": [
          {
            "name": "_placeholder",
            "dataType": "string",
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[_placeholder]",
            "isHidden": true,
            "lineageTag": "dbd7f42c-9dfa-4c44-aad4-a3562a1fad6b",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "S&OP Metrics",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "ROW ( \"_placeholder\", BLANK () )"
            }
          }
        ],
        "measures": [
          {
            "name": "Orders",
            "expression": "COUNTROWS ( fact_orders )",
            "formatString": "#,0",
            "displayFolder": "Volume",
            "description": "Count of booked projects in context.",
            "lineageTag": "f5603812-fb96-4691-9095-e168827011d8"
          },
          {
            "name": "MW Booked",
            "expression": "SUM ( fact_orders[mw] )",
            "formatString": "#,0.0",
            "displayFolder": "Volume",
            "description": "Nameplate MW on booked orders.",
            "lineageTag": "846f2d65-faf8-450b-b0eb-65dffba870e5"
          },
          {
            "name": "Order Value",
            "expression": "SUM ( fact_orders[order_value] )",
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Volume",
            "description": "Booked order value.",
            "lineageTag": "ab5a769d-3b33-476c-afda-4ca5124bb73c"
          },
          {
            "name": "Material Committed",
            "expression": "SUM ( fact_orders[material_committed] )",
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Volume",
            "description": "Order value times the material rate from the case study.",
            "lineageTag": "e15fe653-4b74-44ee-9459-1101d1d918a4"
          },
          {
            "name": "Open Backlog $",
            "expression": [
              "VAR LastBooked =",
              "    CALCULATE ( MAX ( fact_orders[booked_key] ), REMOVEFILTERS ( dim_date ) )",
              "VAR AsOf = MIN ( MAX ( dim_date[date] ), LastBooked )",
              "RETURN",
              "CALCULATE (",
              "    SUMX (",
              "        FILTER (",
              "            fact_orders,",
              "            fact_orders[booked_key] <= AsOf",
              "                && NOT fact_orders[cancelled]",
              "                && ( ISBLANK ( fact_orders[actual_key] )",
              "                     || fact_orders[actual_key] > AsOf )",
              "        ),",
              "        fact_orders[order_value]",
              "    ),",
              "    REMOVEFILTERS ( dim_date )",
              ")"
            ],
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Backlog",
            "description": "Booked on or before the date, not cancelled, not yet converted. Cancelled orders are excluded from both sides; leaving them in the booked side overstates backlog permanently, since they never convert. The as-of date clamps to the last booked month: dim_date has to run out to 2028 to cover conversions, and an unfiltered MAX over it asked for backlog as of a date two years past the end of the book, which nothing satisfies.",
            "lineageTag": "72300e9b-70a5-4654-89a6-30a4b971055c"
          },
          {
            "name": "Open Backlog Material",
            "expression": "[Open Backlog $] * 0.5",
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Backlog",
            "description": "Material value of open backlog.",
            "lineageTag": "a024bbc8-5018-491e-8793-40aa54be150a"
          },
          {
            "name": "Material at Risk",
            "expression": [
              "VAR LastBooked =",
              "    CALCULATE ( MAX ( fact_orders[booked_key] ), REMOVEFILTERS ( dim_date ) )",
              "VAR AsOf = MIN ( MAX ( dim_date[date] ), LastBooked )",
              "RETURN",
              "CALCULATE (",
              "    SUMX (",
              "        FILTER (",
              "            fact_orders,",
              "            fact_orders[booked_key] <= AsOf",
              "                && NOT fact_orders[cancelled]",
              "                && ( ISBLANK ( fact_orders[actual_key] )",
              "                     || fact_orders[actual_key] > AsOf )",
              "                && fact_orders[expected_key] <= AsOf",
              "        ),",
              "        fact_orders[material_committed]",
              "    ),",
              "    REMOVEFILTERS ( dim_date )",
              ")"
            ],
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Backlog",
            "description": "Open orders already past their promised date. Filtered on the promised date, not on realised slip: slip is only knowable after the fact, and a KPI built on it reports something no planner could have produced.",
            "lineageTag": "360ff801-2c25-4b1e-a80c-534f16e2e847"
          },
          {
            "name": "Converted $",
            "expression": [
              "CALCULATE (",
              "    SUM ( fact_orders[order_value] ),",
              "    USERELATIONSHIP ( fact_orders[actual_key], dim_date[date] ),",
              "    fact_orders[cancelled] = FALSE",
              ")"
            ],
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Flow",
            "description": "Order value converting in the month, using the actual conversion date.",
            "lineageTag": "491d675e-432f-42e5-81f9-99e90e035e74"
          },
          {
            "name": "Book to Bill",
            "expression": "DIVIDE ( [Order Value], [Converted $] )",
            "formatString": "0.00",
            "displayFolder": "Flow",
            "description": "Booked over converted. Above 1.0 the book is growing.",
            "lineageTag": "087bd4d2-74cd-4109-8f69-9f02bd5e1551"
          },
          {
            "name": "Requirement P50",
            "expression": [
              "CALCULATE ( SUM ( fact_forecast[p50] ),",
              "    fact_forecast[scope] = \"TOTAL\", fact_forecast[layer] = \"all\" )"
            ],
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Forecast",
            "description": "Median forward material requirement.",
            "lineageTag": "e0d1a2ec-7a1d-4001-88fe-7ab6594c91f6"
          },
          {
            "name": "Requirement P10",
            "expression": [
              "CALCULATE ( SUM ( fact_forecast[p10] ),",
              "    fact_forecast[scope] = \"TOTAL\", fact_forecast[layer] = \"all\" )"
            ],
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Forecast",
            "description": "Low end of the stated 80% interval.",
            "lineageTag": "aa3843a5-0b7d-4410-9748-08d1a0eecfef"
          },
          {
            "name": "Requirement P90",
            "expression": [
              "CALCULATE ( SUM ( fact_forecast[p90] ),",
              "    fact_forecast[scope] = \"TOTAL\", fact_forecast[layer] = \"all\" )"
            ],
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Forecast",
            "description": "High end of the stated 80% interval.",
            "lineageTag": "de7b8079-b217-4f88-a345-016249966720"
          },
          {
            "name": "Interval Width",
            "expression": "[Requirement P90] - [Requirement P10]",
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Forecast",
            "description": "Width of the stated 80% interval.",
            "lineageTag": "447ef87b-8173-4fbf-8adf-5ca0d8a1a2c9"
          },
          {
            "name": "Firm Share",
            "expression": [
              "VAR Firm =",
              "    CALCULATE ( SUM ( fact_forecast[p50] ),",
              "        fact_forecast[scope] = \"TOTAL\", fact_forecast[layer] = \"firm\" )",
              "RETURN DIVIDE ( Firm, [Requirement P50] )"
            ],
            "formatString": "0%",
            "displayFolder": "Forecast",
            "description": "Share of the month's requirement already on booked orders.",
            "lineageTag": "ba218b02-b632-4c36-ac9a-8cb21df63c14"
          },
          {
            "name": "Sum of Regional P90",
            "expression": [
              "CALCULATE (",
              "    SUM ( fact_forecast[p90] ),",
              "    REMOVEFILTERS ( fact_forecast[scope] ),",
              "    fact_forecast[scope] IN { \"North America\", \"EMEA\", \"APAC\", \"LATAM\" },",
              "    fact_forecast[layer] = \"all\"",
              ")"
            ],
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Forecast",
            "description": "Adding the four regional P90s together.",
            "lineageTag": "8391da6c-bcd8-431f-881e-91c1970019a2"
          },
          {
            "name": "Quantile Overstatement %",
            "expression": "DIVIDE ( [Sum of Regional P90] - [Requirement P90], [Requirement P90] )",
            "formatString": "0.0%",
            "displayFolder": "Forecast",
            "description": "How much adding regional worst cases overstates the portfolio worst case. Quantiles do not add: the regions do not all run late in the same month. The gap is material that would be bought and not needed.",
            "lineageTag": "8d588e80-d31f-4763-856d-389749c9b0d7"
          },
          {
            "name": "Slip P50",
            "expression": [
              "PERCENTILEX.INC (",
              "    FILTER ( fact_orders, fact_orders[cancelled] = FALSE ),",
              "    fact_orders[slip_months], 0.5",
              ")"
            ],
            "formatString": "0.0",
            "displayFolder": "Slip",
            "description": "Median schedule slip, in months.",
            "lineageTag": "ce9a95fd-54ab-4cd7-b8e2-01ccc1d3a6af"
          },
          {
            "name": "Slip P90",
            "expression": [
              "PERCENTILEX.INC (",
              "    FILTER ( fact_orders, fact_orders[cancelled] = FALSE ),",
              "    fact_orders[slip_months], 0.9",
              ")"
            ],
            "formatString": "0.0",
            "displayFolder": "Slip",
            "description": "90th percentile schedule slip. The number a commitment horizon is set on.",
            "lineageTag": "ec401761-f809-425f-9ba0-208cda597077"
          },
          {
            "name": "Regional Blend P90",
            "expression": [
              "VAR Rgn = SELECTEDVALUE ( dim_market[region] )",
              "RETURN",
              "CALCULATE (",
              "    [Slip P90],",
              "    REMOVEFILTERS ( dim_market ),",
              "    dim_market[region] = Rgn",
              ")"
            ],
            "formatString": "0.0",
            "displayFolder": "Slip",
            "description": "The same P90 computed at region level. Where a region holds more than one market it describes neither of them: APAC blends Australia and India into a figure that runs early on one and late on the other.",
            "lineageTag": "0bdb6b31-f887-4f84-84dc-f8a194f22009"
          },
          {
            "name": "Blend Gap",
            "expression": "[Slip P90] - [Regional Blend P90]",
            "formatString": "+0.0;-0.0",
            "displayFolder": "Slip",
            "description": "Months between a market's own P90 and the regional figure it would be planned on.",
            "lineageTag": "615d9c06-3814-4b9e-a4eb-7fd924c43cb9"
          },
          {
            "name": "Expected MW",
            "expression": "SUM ( fact_lookback[expected_mw] )",
            "formatString": "#,0.0",
            "displayFolder": "Realization",
            "description": "MW the order book expected to convert.",
            "lineageTag": "564022d0-2ea5-4563-b1f3-917fd112e74d"
          },
          {
            "name": "Actual MW",
            "expression": "SUM ( fact_lookback[actual_mw] )",
            "formatString": "#,0.0",
            "displayFolder": "Realization",
            "description": "MW that actually converted.",
            "lineageTag": "978247ba-b6c4-4f5d-a834-228b9d2b6756"
          },
          {
            "name": "Realization Rate",
            "expression": "DIVIDE ( [Actual MW], [Expected MW] )",
            "formatString": "0.0%",
            "displayFolder": "Realization",
            "description": "Measured, not assumed. This is the number a planning cycle usually picks.",
            "lineageTag": "cec94dae-77a5-468c-938a-183e8b1754e4"
          },
          {
            "name": "Bias MW",
            "expression": "SUM ( fact_lookback[bias_mw] )",
            "formatString": "+#,0.0;-#,0.0",
            "displayFolder": "Realization",
            "description": "Actual minus expected, in MW.",
            "lineageTag": "39c2106a-23cc-4fc7-8805-3865a49f3163"
          },
          {
            "name": "Cumulative Bias MW",
            "expression": [
              "CALCULATE (",
              "    [Bias MW],",
              "    dim_date[date] <= MAX ( dim_date[date] ),",
              "    REMOVEFILTERS ( dim_date )",
              ")"
            ],
            "formatString": "+#,0.0;-#,0.0",
            "displayFolder": "Realization",
            "description": "Running total of bias. A region with persistent drift shows here as a line that does not return to zero.",
            "lineageTag": "befade5f-8ab6-46dd-a363-e205286f9875"
          },
          {
            "name": "Realization Assumption",
            "expression": "SELECTEDVALUE ( 'Realization Scenario'[Realization Scenario], 0.85 )",
            "formatString": "0%",
            "displayFolder": "Scenario",
            "description": "The rate selected on the slider.",
            "lineageTag": "e8e3dfbc-d8cd-44dd-b157-6e26cb7ff318"
          },
          {
            "name": "Material at Assumption",
            "expression": "[Open Backlog Material] * [Realization Assumption]",
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Scenario",
            "description": "Material implied by the chosen realization rate.",
            "lineageTag": "8d5d5c90-c116-4c67-b738-2a1030205de0"
          },
          {
            "name": "Exposure vs Full Commit",
            "expression": "[Open Backlog Material] - [Material at Assumption]",
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Scenario",
            "description": "Distance between committing against the whole book and committing against the assumption. This is the exposure the assumption controls.",
            "lineageTag": "1ff9998d-9bf5-4f6a-8519-9d844df60945"
          },
          {
            "name": "Forecasts Scored",
            "expression": "COUNTROWS ( fact_coverage )",
            "formatString": "#,0",
            "displayFolder": "Coverage",
            "description": "Walk-forward forecasts scored against what the month turned out to be.",
            "lineageTag": "1d8062b0-1660-4cea-90d0-25bb8684cd29"
          },
          {
            "name": "Distinct Outcome Months",
            "expression": "DISTINCTCOUNT ( fact_coverage[month] )",
            "formatString": "#,0",
            "displayFolder": "Coverage",
            "description": "Overlapping six-month windows score the same month up to six times, so this is well below the number of forecasts. It is the effective sample size, and the reason no correction is fitted to the interval.",
            "lineageTag": "68e617d1-debf-420c-8664-715837165af4"
          },
          {
            "name": "Coverage 80%",
            "expression": "DIVIDE ( SUM ( fact_coverage[inside_80] ), [Forecasts Scored] )",
            "formatString": "0.0%",
            "displayFolder": "Coverage",
            "description": "Share of forecasts the stated 80% interval contained.",
            "lineageTag": "96dc7ca7-ee9c-4c17-8b7f-abdaea553b19"
          },
          {
            "name": "Coverage 50%",
            "expression": "DIVIDE ( SUM ( fact_coverage[inside_50] ), [Forecasts Scored] )",
            "formatString": "0.0%",
            "displayFolder": "Coverage",
            "description": "Share the stated 50% interval contained.",
            "lineageTag": "3063fc75-fe0d-4e2f-a88f-8f2fdfd09e1e"
          },
          {
            "name": "Misses High",
            "expression": [
              "CALCULATE ( COUNTROWS ( fact_coverage ),",
              "    FILTER ( fact_coverage, fact_coverage[actual] > fact_coverage[p90] ) )"
            ],
            "formatString": "#,0",
            "displayFolder": "Coverage",
            "description": "Outcomes above the interval.",
            "lineageTag": "e22a3bae-f4c2-40e3-a6d6-228bc69d1788"
          },
          {
            "name": "Misses Low",
            "expression": [
              "CALCULATE ( COUNTROWS ( fact_coverage ),",
              "    FILTER ( fact_coverage, fact_coverage[actual] < fact_coverage[p10] ) )"
            ],
            "formatString": "#,0",
            "displayFolder": "Coverage",
            "description": "Outcomes below the interval.",
            "lineageTag": "7af77384-5031-414e-a8f2-594fb9278d12"
          },
          {
            "name": "Median Error",
            "expression": "MEDIAN ( fact_coverage[error] )",
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Coverage",
            "description": "Median of actual minus P50. Near zero can hide a front end that runs low early and high late, because the halves cancel.",
            "lineageTag": "e5532a11-f0fc-466e-9479-1a4c4ce6857b"
          },
          {
            "name": "Mean Error",
            "expression": "AVERAGE ( fact_coverage[error] )",
            "formatString": "\\$#,0,,\"M\"",
            "displayFolder": "Coverage",
            "description": "Mean of actual minus P50.",
            "lineageTag": "aca44df2-61be-4907-b644-bed5d3ceddb3"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "orders_booked_date",
        "fromTable": "fact_orders",
        "fromColumn": "booked_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "orders_expected_date",
        "fromTable": "fact_orders",
        "fromColumn": "expected_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": false,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "orders_actual_date",
        "fromTable": "fact_orders",
        "fromColumn": "actual_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": false,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "orders_market",
        "fromTable": "fact_orders",
        "fromColumn": "market",
        "toTable": "dim_market",
        "toColumn": "market_key",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "forecast_date",
        "fromTable": "fact_forecast",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "coverage_date",
        "fromTable": "fact_coverage",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "coverage_cutoff",
        "fromTable": "fact_coverage",
        "fromColumn": "cutoff_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": false,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "lookback_date",
        "fromTable": "fact_lookback",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "lookback_market",
        "fromTable": "fact_lookback",
        "fromColumn": "market",
        "toTable": "dim_market",
        "toColumn": "market_key",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      }
    ],
    "expressions": [],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_date\", \"dim_market\", \"fact_orders\", \"fact_forecast\", \"fact_coverage\", \"fact_lookback\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ]
  }
}
