{
  "name": "SemanticModel",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "collation": "Latin1_General_100_BIN2_UTF8",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_date",
        "lineageTag": "3ce0d1a9-da66-4264-9a58-8c313eb398e4",
        "columns": [
          {
            "name": "date_key",
            "dataType": "dateTime",
            "sourceColumn": "date_key",
            "lineageTag": "82aee2da-9c75-4cfd-a3dc-9b89bc8f510c",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "lineageTag": "75dc7bf1-8ff3-4f5a-960d-6b8b7ebfafe1",
            "summarizeBy": "sum"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "lineageTag": "59f7208f-86c2-4750-b4af-1d7b3da53b8a",
            "summarizeBy": "none"
          },
          {
            "name": "month_no",
            "dataType": "int64",
            "sourceColumn": "month_no",
            "lineageTag": "f266a3d4-bbeb-4fda-9d76-6ac618422a9e",
            "summarizeBy": "sum"
          },
          {
            "name": "month_name",
            "dataType": "string",
            "sourceColumn": "month_name",
            "lineageTag": "1217e246-0289-4a70-baa3-9532909c302f",
            "summarizeBy": "none"
          },
          {
            "name": "year_month",
            "dataType": "string",
            "sourceColumn": "year_month",
            "lineageTag": "0daed2a8-11e2-45ad-8aea-d5a2ddad41fb",
            "summarizeBy": "none",
            "sortByColumn": "year_month_sort"
          },
          {
            "name": "fy_label",
            "dataType": "string",
            "sourceColumn": "fy_label",
            "lineageTag": "c9371c58-7dd3-453d-8494-83ecd0bc3c69",
            "summarizeBy": "none"
          },
          {
            "name": "year_month_sort",
            "dataType": "int64",
            "sourceColumn": "year_month_sort",
            "lineageTag": "f3f6fd22-dc29-43f3-994a-868efa01f60a",
            "summarizeBy": "sum"
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "lineageTag": "691b5327-e2ff-483c-b7ad-8369c446b5b6",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          }
        ],
        "partitions": [
          {
            "name": "dim_date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\dim_date.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"date_key\", type date}, {\"year\", Int64.Type}, {\"quarter\", type text}, {\"month_no\", Int64.Type}, {\"month_name\", type text}, {\"year_month\", type text}, {\"fy_label\", type text}, {\"year_month_sort\", Int64.Type}, {\"date\", type date}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "dataCategory": "Time"
      },
      {
        "name": "dim_market",
        "lineageTag": "9994c65a-842c-4734-bbaf-75f1402f9c3a",
        "columns": [
          {
            "name": "market_key",
            "dataType": "string",
            "sourceColumn": "market_key",
            "lineageTag": "c1b14929-ac87-422b-91d8-88adf047dc43",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "market",
            "dataType": "string",
            "sourceColumn": "market",
            "lineageTag": "b24b6e24-e2a3-47eb-8571-2a433224466b",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "lineageTag": "bb9c77d1-2997-468c-b17f-6aeaf726cb75",
            "summarizeBy": "none"
          },
          {
            "name": "tracked_separately",
            "dataType": "string",
            "sourceColumn": "tracked_separately",
            "lineageTag": "5c2dc102-1a1d-472a-9e0c-b4fea5a0aea9",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "dim_market",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\dim_market.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"market_key\", type text}, {\"market\", type text}, {\"region\", type text}, {\"tracked_separately\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_orders",
        "lineageTag": "8d2b0d0a-6499-4fd5-9e6b-c3714d259ed9",
        "columns": [
          {
            "name": "order_id",
            "dataType": "string",
            "sourceColumn": "order_id",
            "lineageTag": "400ab07e-f94c-435a-9627-9293b1c33ccd",
            "summarizeBy": "none"
          },
          {
            "name": "market",
            "dataType": "string",
            "sourceColumn": "market",
            "lineageTag": "2ba396b2-0d26-4c8e-b524-ad37310fb42d",
            "summarizeBy": "none"
          },
          {
            "name": "booked_key",
            "dataType": "dateTime",
            "sourceColumn": "booked_key",
            "lineageTag": "a1f17a34-f512-4605-a328-4a2b4991741c",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd",
            "isHidden": true
          },
          {
            "name": "expected_key",
            "dataType": "dateTime",
            "sourceColumn": "expected_key",
            "lineageTag": "242cde23-5d9a-446d-b987-e0ee02c2c260",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd",
            "isHidden": true
          },
          {
            "name": "actual_key",
            "dataType": "dateTime",
            "sourceColumn": "actual_key",
            "lineageTag": "0796421b-ea49-4cd4-8925-142962945db1",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd",
            "isHidden": true
          },
          {
            "name": "mw",
            "dataType": "double",
            "sourceColumn": "mw",
            "lineageTag": "8fca76bc-0311-4a06-976a-ff660610bdfd",
            "summarizeBy": "sum"
          },
          {
            "name": "order_value",
            "dataType": "double",
            "sourceColumn": "order_value",
            "lineageTag": "2c911d23-b0fc-4d01-9cbf-c4cf88ff1700",
            "summarizeBy": "sum"
          },
          {
            "name": "material_committed",
            "dataType": "double",
            "sourceColumn": "material_committed",
            "lineageTag": "b13502e3-eecf-4a79-a04b-d09f92c15c9d",
            "summarizeBy": "sum"
          },
          {
            "name": "promised_months",
            "dataType": "int64",
            "sourceColumn": "promised_months",
            "lineageTag": "fff740ed-71d9-4190-87ec-596fda32cf60",
            "summarizeBy": "sum"
          },
          {
            "name": "slip_months",
            "dataType": "double",
            "sourceColumn": "slip_months",
            "lineageTag": "40a4113a-e03c-46c6-8698-c1fa37f85594",
            "summarizeBy": "sum"
          },
          {
            "name": "cancelled",
            "dataType": "boolean",
            "sourceColumn": "cancelled",
            "lineageTag": "60e44d34-f463-43f8-a41a-b2539ac48778",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "dataType": "string",
            "sourceColumn": "status",
            "lineageTag": "f5cc078e-9851-4415-821a-7d18c9471630",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "fact_orders",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\fact_orders.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"order_id\", type text}, {\"market\", type text}, {\"booked_key\", type date}, {\"expected_key\", type date}, {\"actual_key\", type date}, {\"mw\", type number}, {\"order_value\", type number}, {\"material_committed\", type number}, {\"promised_months\", Int64.Type}, {\"slip_months\", type number}, {\"cancelled\", type logical}, {\"status\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "isHidden": false
      },
      {
        "name": "fact_forecast",
        "lineageTag": "20951c03-ffb4-4294-b4a9-d861d656ab60",
        "columns": [
          {
            "name": "month",
            "dataType": "dateTime",
            "sourceColumn": "month",
            "lineageTag": "3db3a65f-6ffd-486c-a0bc-f9d66266cc79",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "date_key",
            "dataType": "dateTime",
            "sourceColumn": "date_key",
            "lineageTag": "6ed40f97-fc39-4bd4-83eb-6c9a3d53d06f",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "scope",
            "dataType": "string",
            "sourceColumn": "scope",
            "lineageTag": "7d1fd92e-9b04-46b7-ba9f-5d66826d632d",
            "summarizeBy": "none"
          },
          {
            "name": "layer",
            "dataType": "string",
            "sourceColumn": "layer",
            "lineageTag": "d39e727a-e651-4979-a346-b17695dd66e1",
            "summarizeBy": "none"
          },
          {
            "name": "p10",
            "dataType": "double",
            "sourceColumn": "p10",
            "lineageTag": "60d8ecfc-f947-4cfe-bac8-fd2e6ed13b83",
            "summarizeBy": "sum"
          },
          {
            "name": "p25",
            "dataType": "double",
            "sourceColumn": "p25",
            "lineageTag": "e4e6afdb-1016-48b1-aa4e-547b2b96271d",
            "summarizeBy": "sum"
          },
          {
            "name": "p50",
            "dataType": "double",
            "sourceColumn": "p50",
            "lineageTag": "621932bc-4164-4ac4-8e91-a2a0bcc68ea3",
            "summarizeBy": "sum"
          },
          {
            "name": "p75",
            "dataType": "double",
            "sourceColumn": "p75",
            "lineageTag": "53e89d67-086d-4e24-a2ba-4a994f6946f0",
            "summarizeBy": "sum"
          },
          {
            "name": "p90",
            "dataType": "double",
            "sourceColumn": "p90",
            "lineageTag": "317770c2-4a62-47d8-8df0-6f1e8e395be7",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "fact_forecast",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\fact_forecast.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"month\", type date}, {\"date_key\", type date}, {\"scope\", type text}, {\"layer\", type text}, {\"p10\", type number}, {\"p25\", type number}, {\"p50\", type number}, {\"p75\", type number}, {\"p90\", type number}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "isHidden": false
      },
      {
        "name": "fact_coverage",
        "lineageTag": "ac0d9f6d-d66a-4645-b9b3-97a1a6b5c373",
        "columns": [
          {
            "name": "cutoff",
            "dataType": "dateTime",
            "sourceColumn": "cutoff",
            "lineageTag": "03fd4f32-b9fc-4515-8aa2-c52767926eea",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "month",
            "dataType": "dateTime",
            "sourceColumn": "month",
            "lineageTag": "465d4193-4054-4e77-9299-1e1afea55ac0",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "cutoff_key",
            "dataType": "dateTime",
            "sourceColumn": "cutoff_key",
            "lineageTag": "729186f0-ed64-403a-8bd4-4903e759c3ee",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd",
            "isHidden": true
          },
          {
            "name": "date_key",
            "dataType": "dateTime",
            "sourceColumn": "date_key",
            "lineageTag": "6d211371-4c81-4077-9a34-7ebb012f260e",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "months_ahead",
            "dataType": "int64",
            "sourceColumn": "months_ahead",
            "lineageTag": "00df42a1-eff0-4a1d-99b6-0e4619da24b1",
            "summarizeBy": "sum"
          },
          {
            "name": "actual",
            "dataType": "double",
            "sourceColumn": "actual",
            "lineageTag": "6bda8fcf-e9c5-4322-893e-f1bbf091e5c9",
            "summarizeBy": "sum"
          },
          {
            "name": "p10",
            "dataType": "double",
            "sourceColumn": "p10",
            "lineageTag": "6f575bab-fa41-49ca-a219-c6f277a0a26d",
            "summarizeBy": "sum"
          },
          {
            "name": "p25",
            "dataType": "double",
            "sourceColumn": "p25",
            "lineageTag": "219ab17e-2297-45d6-a2ce-98214e664efa",
            "summarizeBy": "sum"
          },
          {
            "name": "p50",
            "dataType": "double",
            "sourceColumn": "p50",
            "lineageTag": "e7cad439-cdee-4466-b652-95331960a28a",
            "summarizeBy": "sum"
          },
          {
            "name": "p75",
            "dataType": "double",
            "sourceColumn": "p75",
            "lineageTag": "be3dae21-56c0-4f83-bcc2-02c5ccd7c053",
            "summarizeBy": "sum"
          },
          {
            "name": "p90",
            "dataType": "double",
            "sourceColumn": "p90",
            "lineageTag": "c45dff7c-e558-4c8d-a6ad-13749fd73a53",
            "summarizeBy": "sum"
          },
          {
            "name": "error",
            "dataType": "double",
            "sourceColumn": "error",
            "lineageTag": "dfd2535e-26c4-4df0-b895-ffc056310d40",
            "summarizeBy": "sum"
          },
          {
            "name": "inside_80",
            "dataType": "int64",
            "sourceColumn": "inside_80",
            "lineageTag": "c12cecc3-21ad-476f-b98b-ade9a5c56a44",
            "summarizeBy": "sum"
          },
          {
            "name": "inside_50",
            "dataType": "int64",
            "sourceColumn": "inside_50",
            "lineageTag": "6b86ed2e-bf38-4100-a61f-d3cf1534447b",
            "summarizeBy": "sum"
          },
          {
            "name": "direction",
            "dataType": "string",
            "sourceColumn": "direction",
            "lineageTag": "277270e2-3b33-46c6-8410-b15e8a8aec0b",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "fact_coverage",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\fact_coverage.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"cutoff\", type date}, {\"month\", type date}, {\"cutoff_key\", type date}, {\"date_key\", type date}, {\"months_ahead\", Int64.Type}, {\"actual\", type number}, {\"p10\", type number}, {\"p25\", type number}, {\"p50\", type number}, {\"p75\", type number}, {\"p90\", type number}, {\"error\", type number}, {\"inside_80\", Int64.Type}, {\"inside_50\", Int64.Type}, {\"direction\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "isHidden": false
      },
      {
        "name": "fact_lookback",
        "lineageTag": "58c7cde6-c573-4f92-b606-7345ba6f5978",
        "columns": [
          {
            "name": "market",
            "dataType": "string",
            "sourceColumn": "market",
            "lineageTag": "5f51ede5-8941-49c1-aad2-2718ad86105c",
            "summarizeBy": "none"
          },
          {
            "name": "month",
            "dataType": "dateTime",
            "sourceColumn": "month",
            "lineageTag": "f41b42a8-ea50-48dc-a398-de356604fa18",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "date_key",
            "dataType": "dateTime",
            "sourceColumn": "date_key",
            "lineageTag": "c611d3ec-807c-4db9-9644-157a5c1f0e19",
            "summarizeBy": "none",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "expected_mw",
            "dataType": "double",
            "sourceColumn": "expected_mw",
            "lineageTag": "b5bb3324-eb69-4e8c-96ed-c407e60f8510",
            "summarizeBy": "sum"
          },
          {
            "name": "actual_mw",
            "dataType": "double",
            "sourceColumn": "actual_mw",
            "lineageTag": "d4ea28da-4f85-4af9-aab1-4ba65558ca0c",
            "summarizeBy": "sum"
          },
          {
            "name": "realization",
            "dataType": "double",
            "sourceColumn": "realization",
            "lineageTag": "748df0fb-54bd-41e7-bcc7-a0fcd68c91b7",
            "summarizeBy": "sum"
          },
          {
            "name": "bias_mw",
            "dataType": "double",
            "sourceColumn": "bias_mw",
            "lineageTag": "4133aa6a-cfdd-4094-9268-14cdc14af2c1",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "fact_lookback",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(",
                "        File.Contents(\"C:\\Users\\stava\\OneDrive\\Documents\\75TH\\Job-Search-Relocation\\nextpower_sim\\pbi\\data\\fact_lookback.csv\"),",
                "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                "    ),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"market\", type text}, {\"month\", type date}, {\"date_key\", type date}, {\"expected_mw\", type number}, {\"actual_mw\", type number}, {\"realization\", type number}, {\"bias_mw\", type number}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "isHidden": false
      },
      {
        "name": "Realization Scenario",
        "lineageTag": "92b36686-48a1-4d45-8505-7862931a322d",
        "columns": [
          {
            "name": "Realization Scenario",
            "dataType": "double",
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Realization Scenario]",
            "formatString": "0%",
            "lineageTag": "25a500d8-0b47-4aea-bd66-37683c40d152",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Realization Scenario",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "SELECTCOLUMNS (\n    GENERATESERIES ( 0.55, 1, 0.05 ),\n    \"Realization Scenario\", [Value]\n)"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "69d40012d5c24ba6a6e167cfacdfb882"
          }
        ]
      },
      {
        "name": "S&OP Metrics",
        "lineageTag": "d20546a4-c1ab-4d88-bbfe-88b57a8fc715",
        "columns": [
          {
            "name": "_placeholder",
            "dataType": "string",
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[_placeholder]",
            "isHidden": true,
            "lineageTag": "1fd326ef-1c6f-41b4-8038-175f411aa85a",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "S&OP Metrics",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "ROW ( \"_placeholder\", BLANK () )"
            }
          }
        ],
        "measures": [
          {
            "name": "Orders",
            "expression": "COUNTROWS ( fact_orders )",
            "formatString": "#,0",
            "displayFolder": "Volume",
            "description": "Count of booked projects in context.",
            "lineageTag": "a19c36be-d0dc-43cd-86db-d483b62e1e1c"
          },
          {
            "name": "MW Booked",
            "expression": "SUM ( fact_orders[mw] )",
            "formatString": "#,0.0",
            "displayFolder": "Volume",
            "description": "Nameplate MW on booked orders.",
            "lineageTag": "7266ee94-f29c-4f29-b2da-98c16e8ec9af"
          },
          {
            "name": "Order Value",
            "expression": "SUM ( fact_orders[order_value] )",
            "formatString": "\\$#,##0",
            "displayFolder": "Volume",
            "description": "Booked order value.",
            "lineageTag": "80d148c0-aea9-483b-a310-245b21e57085"
          },
          {
            "name": "Material Committed",
            "expression": "SUM ( fact_orders[material_committed] )",
            "formatString": "\\$#,##0",
            "displayFolder": "Volume",
            "description": "Order value times the material rate from the case study.",
            "lineageTag": "0985c448-157b-4681-89af-668ed76dd65a"
          },
          {
            "name": "Open Backlog $",
            "expression": [
              "VAR LastBooked =",
              "    CALCULATE ( MAX ( fact_orders[booked_key] ), REMOVEFILTERS ( dim_date ) )",
              "VAR AsOf = MIN ( MAX ( dim_date[date] ), LastBooked )",
              "RETURN",
              "CALCULATE (",
              "    SUMX (",
              "        FILTER (",
              "            fact_orders,",
              "            fact_orders[booked_key] <= AsOf",
              "                && NOT fact_orders[cancelled]",
              "                && ( ISBLANK ( fact_orders[actual_key] )",
              "                     || fact_orders[actual_key] > AsOf )",
              "        ),",
              "        fact_orders[order_value]",
              "    ),",
              "    REMOVEFILTERS ( dim_date )",
              ")"
            ],
            "formatString": "\\$#,##0",
            "displayFolder": "Backlog",
            "description": "Booked on or before the date, not cancelled, not yet converted. Cancelled orders are excluded from both sides; leaving them in the booked side overstates backlog permanently, since they never convert. The as-of date clamps to the last booked month: dim_date has to run out to 2028 to cover conversions, and an unfiltered MAX over it asked for backlog as of a date two years past the end of the book, which nothing satisfies.",
            "lineageTag": "d0e1d76d-5ad4-4ce0-ab87-2acf9760c71b"
          },
          {
            "name": "Open Backlog Material",
            "expression": "[Open Backlog $] * 0.5",
            "formatString": "\\$#,##0",
            "displayFolder": "Backlog",
            "description": "Material value of open backlog.",
            "lineageTag": "95dad899-fc48-4434-9127-bcb25094e06a"
          },
          {
            "name": "Material at Risk",
            "expression": [
              "VAR LastBooked =",
              "    CALCULATE ( MAX ( fact_orders[booked_key] ), REMOVEFILTERS ( dim_date ) )",
              "VAR AsOf = MIN ( MAX ( dim_date[date] ), LastBooked )",
              "RETURN",
              "CALCULATE (",
              "    SUMX (",
              "        FILTER (",
              "            fact_orders,",
              "            fact_orders[booked_key] <= AsOf",
              "                && NOT fact_orders[cancelled]",
              "                && ( ISBLANK ( fact_orders[actual_key] )",
              "                     || fact_orders[actual_key] > AsOf )",
              "                && fact_orders[expected_key] <= AsOf",
              "        ),",
              "        fact_orders[material_committed]",
              "    ),",
              "    REMOVEFILTERS ( dim_date )",
              ")"
            ],
            "formatString": "\\$#,##0",
            "displayFolder": "Backlog",
            "description": "Open orders already past their promised date. Filtered on the promised date, not on realised slip: slip is only knowable after the fact, and a KPI built on it reports something no planner could have produced.",
            "lineageTag": "34571dce-f451-4131-a5c8-1f4752ba6110"
          },
          {
            "name": "Converted $",
            "expression": [
              "CALCULATE (",
              "    SUM ( fact_orders[order_value] ),",
              "    USERELATIONSHIP ( fact_orders[actual_key], dim_date[date] ),",
              "    fact_orders[cancelled] = FALSE",
              ")"
            ],
            "formatString": "\\$#,##0",
            "displayFolder": "Flow",
            "description": "Order value converting in the month, using the actual conversion date.",
            "lineageTag": "6fc50ada-345e-4e46-875f-cdf117f54c49"
          },
          {
            "name": "Book to Bill",
            "expression": "DIVIDE ( [Order Value], [Converted $] )",
            "formatString": "0.00",
            "displayFolder": "Flow",
            "description": "Booked over converted. Above 1.0 the book is growing.",
            "lineageTag": "81fe3f30-0784-4f5a-90a0-c57630888193"
          },
          {
            "name": "Requirement P50",
            "expression": [
              "CALCULATE ( SUM ( fact_forecast[p50] ),",
              "    fact_forecast[scope] = \"TOTAL\", fact_forecast[layer] = \"all\" )"
            ],
            "formatString": "\\$#,##0",
            "displayFolder": "Forecast",
            "description": "Median forward material requirement.",
            "lineageTag": "d5e55933-3bc0-4088-9044-bf2ddc924a06"
          },
          {
            "name": "Requirement P10",
            "expression": [
              "CALCULATE ( SUM ( fact_forecast[p10] ),",
              "    fact_forecast[scope] = \"TOTAL\", fact_forecast[layer] = \"all\" )"
            ],
            "formatString": "\\$#,##0",
            "displayFolder": "Forecast",
            "description": "Low end of the stated 80% interval.",
            "lineageTag": "e770d40b-3c50-49e4-bbde-4f16c9439b8b"
          },
          {
            "name": "Requirement P90",
            "expression": [
              "CALCULATE ( SUM ( fact_forecast[p90] ),",
              "    fact_forecast[scope] = \"TOTAL\", fact_forecast[layer] = \"all\" )"
            ],
            "formatString": "\\$#,##0",
            "displayFolder": "Forecast",
            "description": "High end of the stated 80% interval.",
            "lineageTag": "d1429a6a-89e3-44aa-905c-a05eee306da8"
          },
          {
            "name": "Interval Width",
            "expression": "[Requirement P90] - [Requirement P10]",
            "formatString": "\\$#,##0",
            "displayFolder": "Forecast",
            "description": "Width of the stated 80% interval.",
            "lineageTag": "6fc6ed32-e2b1-4806-b2b4-5acec0e6c713"
          },
          {
            "name": "Firm Share",
            "expression": [
              "VAR Firm =",
              "    CALCULATE ( SUM ( fact_forecast[p50] ),",
              "        fact_forecast[scope] = \"TOTAL\", fact_forecast[layer] = \"firm\" )",
              "RETURN DIVIDE ( Firm, [Requirement P50] )"
            ],
            "formatString": "0%",
            "displayFolder": "Forecast",
            "description": "Share of the month's requirement already on booked orders.",
            "lineageTag": "1ce30dd2-2f53-465b-aa2a-352978914651"
          },
          {
            "name": "Requirement Next Month",
            "expression": [
              "VAR M1 = CALCULATE ( MIN ( fact_forecast[month] ), REMOVEFILTERS ( ) )",
              "RETURN",
              "CALCULATE (",
              "    SUM ( fact_forecast[p50] ),",
              "    REMOVEFILTERS ( ),",
              "    fact_forecast[scope] = \"TOTAL\",",
              "    fact_forecast[layer] = \"all\",",
              "    fact_forecast[month] = M1",
              ")"
            ],
            "formatString": "\\$#,##0",
            "displayFolder": "Forecast",
            "description": "Median requirement for the first forecast month only. Ignores slicers, because a headline card should say the same thing whatever is filtered.",
            "lineageTag": "93a2edb1-7652-41d0-a4c7-a62c25d8c629"
          },
          {
            "name": "Firm Share Next Month",
            "expression": [
              "VAR M1 = CALCULATE ( MIN ( fact_forecast[month] ), REMOVEFILTERS ( ) )",
              "VAR Firm =",
              "    CALCULATE (",
              "        SUM ( fact_forecast[p50] ),",
              "        REMOVEFILTERS ( ),",
              "        fact_forecast[scope] = \"TOTAL\",",
              "        fact_forecast[layer] = \"firm\",",
              "        fact_forecast[month] = M1",
              "    )",
              "RETURN DIVIDE ( Firm, [Requirement Next Month] )"
            ],
            "formatString": "0%",
            "displayFolder": "Forecast",
            "description": "Share of the first forecast month already sitting on booked orders.",
            "lineageTag": "62514d16-f035-4905-8f1a-5878243d637d"
          },
          {
            "name": "Sum of Regional P90",
            "expression": [
              "CALCULATE (",
              "    SUM ( fact_forecast[p90] ),",
              "    REMOVEFILTERS ( fact_forecast[scope] ),",
              "    fact_forecast[scope] IN { \"North America\", \"EMEA\", \"APAC\", \"LATAM\" },",
              "    fact_forecast[layer] = \"all\"",
              ")"
            ],
            "formatString": "\\$#,##0",
            "displayFolder": "Forecast",
            "description": "Adding the four regional P90s together.",
            "lineageTag": "fe7b4beb-8dd8-4f04-9959-9ba9ab667d45"
          },
          {
            "name": "Quantile Overstatement %",
            "expression": "DIVIDE ( [Sum of Regional P90] - [Requirement P90], [Requirement P90] )",
            "formatString": "0.0%",
            "displayFolder": "Forecast",
            "description": "How much adding regional worst cases overstates the portfolio worst case. Quantiles do not add: the regions do not all run late in the same month. The gap is material that would be bought and not needed.",
            "lineageTag": "69eaebc7-cfa0-48a9-ad1b-1f603e5c5622"
          },
          {
            "name": "Slip P50",
            "expression": [
              "PERCENTILEX.INC (",
              "    FILTER ( fact_orders, fact_orders[cancelled] = FALSE ),",
              "    fact_orders[slip_months], 0.5",
              ")"
            ],
            "formatString": "0.0",
            "displayFolder": "Slip",
            "description": "Median schedule slip, in months.",
            "lineageTag": "c7c4e7a2-ffba-44b8-82fa-2184385e198c"
          },
          {
            "name": "Slip P90",
            "expression": [
              "PERCENTILEX.INC (",
              "    FILTER ( fact_orders, fact_orders[cancelled] = FALSE ),",
              "    fact_orders[slip_months], 0.9",
              ")"
            ],
            "formatString": "0.0",
            "displayFolder": "Slip",
            "description": "90th percentile schedule slip. The number a commitment horizon is set on.",
            "lineageTag": "7f6eed87-b30e-45d2-807d-581f6f9324d3"
          },
          {
            "name": "Regional Blend P90",
            "expression": [
              "VAR Rgn = SELECTEDVALUE ( dim_market[region] )",
              "RETURN",
              "CALCULATE (",
              "    [Slip P90],",
              "    REMOVEFILTERS ( dim_market ),",
              "    dim_market[region] = Rgn",
              ")"
            ],
            "formatString": "0.0",
            "displayFolder": "Slip",
            "description": "The same P90 computed at region level. Where a region holds more than one market it describes neither of them: APAC blends Australia and India into a figure that runs early on one and late on the other.",
            "lineageTag": "9ddb61b7-e7aa-4872-ae06-c4a9682a4527"
          },
          {
            "name": "Blend Gap",
            "expression": "[Slip P90] - [Regional Blend P90]",
            "formatString": "+0.0;-0.0",
            "displayFolder": "Slip",
            "description": "Months between a market's own P90 and the regional figure it would be planned on.",
            "lineageTag": "832338d0-9d3f-4be8-9311-af6ddaf6b990"
          },
          {
            "name": "Expected MW",
            "expression": "SUM ( fact_lookback[expected_mw] )",
            "formatString": "#,0.0",
            "displayFolder": "Realization",
            "description": "MW the order book expected to convert.",
            "lineageTag": "96d792d8-d939-468c-b8bf-c5fb68798ddd"
          },
          {
            "name": "Actual MW",
            "expression": "SUM ( fact_lookback[actual_mw] )",
            "formatString": "#,0.0",
            "displayFolder": "Realization",
            "description": "MW that actually converted.",
            "lineageTag": "10318ec8-cf45-4d6c-b1a1-7fd5ac2faf77"
          },
          {
            "name": "Realization Rate",
            "expression": "DIVIDE ( [Actual MW], [Expected MW] )",
            "formatString": "0.0%",
            "displayFolder": "Realization",
            "description": "Measured, not assumed. This is the number a planning cycle usually picks.",
            "lineageTag": "c73932ed-c61a-4fda-9c35-8e7f5d39e185"
          },
          {
            "name": "Bias MW",
            "expression": "SUM ( fact_lookback[bias_mw] )",
            "formatString": "+#,0.0;-#,0.0",
            "displayFolder": "Realization",
            "description": "Actual minus expected, in MW.",
            "lineageTag": "b6c8b7a4-379b-46a4-b8a8-ec0162831257"
          },
          {
            "name": "Cumulative Bias MW",
            "expression": [
              "CALCULATE (",
              "    [Bias MW],",
              "    dim_date[date] <= MAX ( dim_date[date] ),",
              "    REMOVEFILTERS ( dim_date )",
              ")"
            ],
            "formatString": "+#,0.0;-#,0.0",
            "displayFolder": "Realization",
            "description": "Running total of bias. A region with persistent drift shows here as a line that does not return to zero.",
            "lineageTag": "ed676494-6491-4cee-9495-42ae2ef1eac7"
          },
          {
            "name": "Realization Assumption",
            "expression": "SELECTEDVALUE ( 'Realization Scenario'[Realization Scenario], 0.85 )",
            "formatString": "0%",
            "displayFolder": "Scenario",
            "description": "The rate selected on the slider.",
            "lineageTag": "0abd9162-1312-4830-b592-ae44e687ebb4"
          },
          {
            "name": "Material at Assumption",
            "expression": "[Open Backlog Material] * [Realization Assumption]",
            "formatString": "\\$#,##0",
            "displayFolder": "Scenario",
            "description": "Material implied by the chosen realization rate.",
            "lineageTag": "b759e4c1-ea96-4b0b-abca-3d5ea32af5d2"
          },
          {
            "name": "Exposure vs Full Commit",
            "expression": "[Open Backlog Material] - [Material at Assumption]",
            "formatString": "\\$#,##0",
            "displayFolder": "Scenario",
            "description": "Distance between committing against the whole book and committing against the assumption. This is the exposure the assumption controls.",
            "lineageTag": "f3c07b09-3df0-46ce-a258-039cac69c2e3"
          },
          {
            "name": "Forecasts Scored",
            "expression": "COUNTROWS ( fact_coverage )",
            "formatString": "#,0",
            "displayFolder": "Coverage",
            "description": "Walk-forward forecasts scored against what the month turned out to be.",
            "lineageTag": "646e9b6f-6c9c-4152-b2e7-cb1d790a8b05"
          },
          {
            "name": "Distinct Outcome Months",
            "expression": "DISTINCTCOUNT ( fact_coverage[month] )",
            "formatString": "#,0",
            "displayFolder": "Coverage",
            "description": "Overlapping six-month windows score the same month up to six times, so this is well below the number of forecasts. It is the effective sample size, and the reason no correction is fitted to the interval.",
            "lineageTag": "553b5f5f-a945-4b7f-bfb5-645e6dd61857"
          },
          {
            "name": "Coverage 80%",
            "expression": "DIVIDE ( SUM ( fact_coverage[inside_80] ), [Forecasts Scored] )",
            "formatString": "0.0%",
            "displayFolder": "Coverage",
            "description": "Share of forecasts the stated 80% interval contained.",
            "lineageTag": "c250c093-299e-4a15-ad1d-b423e8dd089e"
          },
          {
            "name": "Coverage 50%",
            "expression": "DIVIDE ( SUM ( fact_coverage[inside_50] ), [Forecasts Scored] )",
            "formatString": "0.0%",
            "displayFolder": "Coverage",
            "description": "Share the stated 50% interval contained.",
            "lineageTag": "8b9ae629-5741-40db-9a33-4cd5912ef22a"
          },
          {
            "name": "Misses High",
            "expression": [
              "CALCULATE ( COUNTROWS ( fact_coverage ),",
              "    FILTER ( fact_coverage, fact_coverage[actual] > fact_coverage[p90] ) )"
            ],
            "formatString": "#,0",
            "displayFolder": "Coverage",
            "description": "Outcomes above the interval.",
            "lineageTag": "68328b9e-8fc4-4896-8f3e-a197e4db8c7b"
          },
          {
            "name": "Misses Low",
            "expression": [
              "CALCULATE ( COUNTROWS ( fact_coverage ),",
              "    FILTER ( fact_coverage, fact_coverage[actual] < fact_coverage[p10] ) )"
            ],
            "formatString": "#,0",
            "displayFolder": "Coverage",
            "description": "Outcomes below the interval.",
            "lineageTag": "4558a3f2-aa62-4d36-9bdb-5ac38ab989dc"
          },
          {
            "name": "Median Error",
            "expression": "MEDIAN ( fact_coverage[error] )",
            "formatString": "\\$#,##0",
            "displayFolder": "Coverage",
            "description": "Median of actual minus P50. Near zero can hide a front end that runs low early and high late, because the halves cancel.",
            "lineageTag": "ea765a4d-d7ca-4b59-9299-4f1a0dd07917"
          },
          {
            "name": "Mean Error",
            "expression": "AVERAGE ( fact_coverage[error] )",
            "formatString": "\\$#,##0",
            "displayFolder": "Coverage",
            "description": "Mean of actual minus P50.",
            "lineageTag": "65e222f2-7649-46ea-ad5d-6f2f5d4009b2"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "orders_booked_date",
        "fromTable": "fact_orders",
        "fromColumn": "booked_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "orders_expected_date",
        "fromTable": "fact_orders",
        "fromColumn": "expected_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": false,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "orders_actual_date",
        "fromTable": "fact_orders",
        "fromColumn": "actual_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": false,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "orders_market",
        "fromTable": "fact_orders",
        "fromColumn": "market",
        "toTable": "dim_market",
        "toColumn": "market_key",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "forecast_date",
        "fromTable": "fact_forecast",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "coverage_date",
        "fromTable": "fact_coverage",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "coverage_cutoff",
        "fromTable": "fact_coverage",
        "fromColumn": "cutoff_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": false,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "lookback_date",
        "fromTable": "fact_lookback",
        "fromColumn": "date_key",
        "toTable": "dim_date",
        "toColumn": "date",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "lookback_market",
        "fromTable": "fact_lookback",
        "fromColumn": "market",
        "toTable": "dim_market",
        "toColumn": "market_key",
        "isActive": true,
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      }
    ],
    "expressions": [],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_date\", \"dim_market\", \"fact_orders\", \"fact_forecast\", \"fact_coverage\", \"fact_lookback\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ]
  }
}
